"""expenses

Revision ID: 0d466811717e
Revises: f24317884942
Create Date: 2026-08-07 19:01:49.363847
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0d466811717e'
down_revision: str | None = 'f24317884942'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Баримтын дугаарлалтын дараалал (Alembic autogenerate үүнийг гаргадаггүй).
    op.execute("CREATE SEQUENCE IF NOT EXISTS expense_number_seq START 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('number', sa.Integer(), server_default=sa.text("nextval('expense_number_seq')"), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('account_code', sa.String(length=16), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('ap_invoice_id', sa.UUID(), nullable=True),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('invoice_no', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('posted_by', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_code'], ['accounts.code'], ),
    sa.ForeignKeyConstraint(['ap_invoice_id'], ['ap_invoices.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_account_code'), 'expenses', ['account_code'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_number'), 'expenses', ['number'], unique=False)
    op.create_index(op.f('ix_expenses_payment_method'), 'expenses', ['payment_method'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_payment_method'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_number'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_account_code'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS expense_number_seq")
