"""payroll_worked_window

Revision ID: 2b3fd0c957b0
Revises: b94017658563
Create Date: 2026-08-08 01:11:49.202319
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2b3fd0c957b0'
down_revision: str | None = 'b94017658563'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_lines', sa.Column('worked_from', sa.Date(), nullable=True))
    op.add_column('payroll_lines', sa.Column('worked_to', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_lines', 'worked_to')
    op.drop_column('payroll_lines', 'worked_from')
    # ### end Alembic commands ###
