"""branches

Revision ID: 8bcc4e12b3e4
Revises: fde9d68918c1
Create Date: 2026-08-07 23:41:04.792089
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8bcc4e12b3e4'
down_revision: str | None = 'fde9d68918c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_index(op.f('ix_branches_is_active'), 'branches', ['is_active'], unique=False)
    op.add_column('employees', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_employees_branch_id'), 'employees', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'branches', ['branch_id'], ['id'])
    op.add_column('expenses', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_expenses_branch_id'), 'expenses', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'branches', ['branch_id'], ['id'])
    op.add_column('pumps', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_pumps_branch_id'), 'pumps', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'pumps', 'branches', ['branch_id'], ['id'])
    op.add_column('sales', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sales_branch_id'), 'sales', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'branches', ['branch_id'], ['id'])
    op.add_column('shifts', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_shifts_branch_id'), 'shifts', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'shifts', 'branches', ['branch_id'], ['id'])
    op.add_column('tanks', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tanks_branch_id'), 'tanks', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'tanks', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tanks', type_='foreignkey')
    op.drop_index(op.f('ix_tanks_branch_id'), table_name='tanks')
    op.drop_column('tanks', 'branch_id')
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_index(op.f('ix_shifts_branch_id'), table_name='shifts')
    op.drop_column('shifts', 'branch_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_branch_id'), table_name='sales')
    op.drop_column('sales', 'branch_id')
    op.drop_constraint(None, 'pumps', type_='foreignkey')
    op.drop_index(op.f('ix_pumps_branch_id'), table_name='pumps')
    op.drop_column('pumps', 'branch_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_branch_id'), table_name='expenses')
    op.drop_column('expenses', 'branch_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_branch_id'), table_name='employees')
    op.drop_column('employees', 'branch_id')
    op.drop_index(op.f('ix_branches_is_active'), table_name='branches')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
