"""payroll

Revision ID: a73454374380
Revises: 0d466811717e
Create Date: 2026-08-07 20:51:39.514218
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a73454374380'
down_revision: str | None = '0d466811717e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('register_no', sa.String(length=32), nullable=True),
    sa.Column('social_no', sa.String(length=32), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('bank_account', sa.String(length=64), nullable=True),
    sa.Column('base_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.create_table('payroll_periods',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('si_employee_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('si_employer_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('pit_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('pit_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('si_employee_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('si_employer_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pit_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_pit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_social', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_payroll_period')
    )
    op.create_index(op.f('ix_payroll_periods_month'), 'payroll_periods', ['month'], unique=False)
    op.create_index(op.f('ix_payroll_periods_status'), 'payroll_periods', ['status'], unique=False)
    op.create_index(op.f('ix_payroll_periods_year'), 'payroll_periods', ['year'], unique=False)
    op.create_table('payroll_lines',
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('worked_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('month_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('earned_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_addition', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('si_employee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('si_employer', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('advance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_deduction', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['payroll_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'employee_id', name='uq_payroll_line')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_lines')
    op.drop_index(op.f('ix_payroll_periods_year'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_status'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_month'), table_name='payroll_periods')
    op.drop_table('payroll_periods')
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
