"""user_branch

Revision ID: b94017658563
Revises: 8bcc4e12b3e4
Create Date: 2026-08-08 00:07:28.279397
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b94017658563'
down_revision: str | None = '8bcc4e12b3e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_column('users', 'branch_id')
    # ### end Alembic commands ###
