"""employee_advances

Revision ID: fde9d68918c1
Revises: a73454374380
Create Date: 2026-08-07 20:57:16.168292
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fde9d68918c1'
down_revision: str | None = 'a73454374380'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_advances',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('advance_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_from', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_advances_advance_date'), 'employee_advances', ['advance_date'], unique=False)
    op.create_index(op.f('ix_employee_advances_employee_id'), 'employee_advances', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_advances_employee_id'), table_name='employee_advances')
    op.drop_index(op.f('ix_employee_advances_advance_date'), table_name='employee_advances')
    op.drop_table('employee_advances')
    # ### end Alembic commands ###
